### PR TITLE
Adds systemd option for init systems, now supports arch platform (Arch Linux)

### PR DESCRIPTION
**Pull request by logankoester**
I had to add [systemd](https://en.wikipedia.org/wiki/Systemd) support to use this cookbook on Arch Linux. Let me know if you have any questions :-)

### CODE REVIEW

**Comment by jslusher** [comment]
Any idea when this will be added? I would like to use this cookbook on centos 7. Thanks for the cookbook!

**Comment by adamkrone** [comment]
@logankoester @jslusher Sorry I haven't replied sooner.

I'm okay with merging this, but before I cut a release for the supermaket, I want to setup centos 7 and possibly arch with Test Kitchen. I'm taking a look right now, but I might not have time to finish it until sometime this weekend.

**Comment by adamkrone** [comment]
@logankoester @jslusher Just wanted to let you know that v0.8.0 is up on the chef supermarket, which includes these updates.

**Comment by logankoester** [comment]
Thanks @adamkrone :smile_cat:

**Pull request merged**
