### PR TITLE
Add checksums for v0.14.0

### PR DESCRIPTION
**Pull request by tgwizard**
There aren't any binaries for `arm`, so I skipped those: https://releases.hashicorp.com/consul-template/0.14.0/

I also updated the script to warn when it cannot find binaries. This makes it easier to detect errors (I initially ran `./scripts/generate-checksums 0.14`).

@adamkrone when do you plan to release a new version?

### CODE REVIEW

**Comment by tgwizard** [comment]
Ping @adamkrone, what do you think?

**Comment by tgwizard** [comment]
Ping @adamkrone

**Comment by arnaud036** [comment]
👍

**Comment by legal90** [comment]
@adamkrone 0.14.0 introduces new API functions. Please, merge this PR and release a new version.

**Comment by adamkrone** [comment]
@tgwizard sorry, I've been out of the loop on this project for a while. I should be releasing a new version in the next few days.

**Comment by tgwizard** [comment]
Thanks for merging, and thanks for the great work @adamkrone!

**Pull request merged**
