### PR TITLE
Drop "supports :reload" from runit_service definition

### PR DESCRIPTION
**Pull request by nmeyerhans**
Drop "supports :reload" from runit_service definition since the runit cookbook does not define a reload_command for runit_service resources.

Otherwise chef runs fail with:
```Generated at 2016-05-26 23:37:59 +0000
Chef::Exceptions::UnsupportedAction: service[consul-template] (dynamically defined) had an error: Chef::Exceptions::UnsupportedAction: #<Chef::Provider::Service::Simple:0x0000000a4972d0> requires a reload_command be set in order to perform a reload
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/mixin/why_run.rb:240:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/mixin/why_run.rb:321:in `block in run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/mixin/why_run.rb:320:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/mixin/why_run.rb:320:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider.rb:155:in `process_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider.rb:133:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:127:in `run_delayed_notification'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:115:in `block in run_delayed_notifications'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:114:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:114:in `run_delayed_notifications'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:104:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:667:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:662:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:662:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:701:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/client.rb:442:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/client.rb:442:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/client.rb:426:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'
```

### CODE REVIEW

**Comment by ptqa** [comment]
@adamkrone any reason why this can not me merged?

**Comment by adamkrone** [comment]
Sorry, I've been out of the loop on this project for a while.

@nmeyerhans can you remove the version increment? I'm going to be releasing v0.11.0 once I merge this and the other outstanding PRs.

Thanks!

**Comment by nmeyerhans** [comment]
@adamkrone Done and pushed in 1dc07ebcd420ca05648638edf5be1381f91d217e

**Comment by adamkrone** [comment]
@nmeyerhans awesome, thanks!

**Pull request merged**
