### PR TITLE
ensure config directory exists

### PR DESCRIPTION
**Pull request by franklinwise**
when I ran this provider I discovered that the config directory didn't exist, so I added the creation if it doesn't exist.

### CODE REVIEW

**Comment by tgwizard** [comment]
The directory is created here: https://github.com/adamkrone/chef-consul-template/blob/master/recipes/service.rb#L45

**Comment by franklinwise** [comment]
Yes, and that creates an ordered dependency between the provider and the service recipe making the provider unusable without setting up the service.  The configs should be created before the service starts anyways.   So if I want to call the provider in a separate recipe to register the config from outside this project, I can't do it without this change.

**Comment by adamkrone** [comment]
Makes sense. Can you just fix the recursive and action lines to be spaces instead of tabs?

Thanks

**Comment by franklinwise** [comment]
updated

**Comment by adamkrone** [comment]
Awesome, thanks again!

**Pull request merged**
