### PR TITLE
Refactor config provider to not reload service incorrectly

### PR DESCRIPTION
**Pull request by tgwizard**
The old reload notification didn't work when when the service provider upstart. The user of `consul_template_config` will now need to now to notify a reload of the consul-template service. **This is a breaking change**, but much cleaner and simpler to reason about. It also will not result in more than one reload (if `:delayed` is used).

The new structure:

```ruby
consul_template_config 'haproxy' do
  templates [{
    source: '/etc/haproxy/haproxy.cfg.ctmpl',
    destination: '/etc/haproxy/haproxy.cfg',
    command: 'service haproxy restart'
  }]
  notifies :reload, 'service[consul-template]', :delayed
end
```

### CODE REVIEW

**Comment by adamkrone** [comment]
@tgwizard Can you give some more information on what you were seeing? I'm not against this change, I'm just curious what issue you encountered.

In any case, I don't think multiple delayed notifications will be a problem. As far as I understand, any additional notifications will be skipped, and should be shown as such in the Chef run log. If you're seeing the same service notification execute multiple times, that's likely a regression in Chef.

**Comment by tgwizard** [comment]
@adamkrone I found two issues.

The first one is multiple `service consul-template reload`. Using `use_inline_resources` in a provider (which we do here) makes it impossible to notify/subscribe to resources outside the provider from resources inside the provider, but possible to send notifications from the actual provider, as in the updated README. It also makes it so that all resources in the provider are executed fully, including notifications, before the provider is considered done. (Or at least this is how I interpret the docs, and how it seems to work when I run it. https://docs.chef.io/lwrp_custom_provider.html#use-inline-resources)

The second issue has to do with the service not being treated as an upstart service inside the provider. The service definition in the provider differs with that in the recipe, that the latter as been configure to be an upstart service (if on ubuntu) and supports reloads. Without this PR I couldn't get

```ruby
consul_template_config 'haproxy' do
  templates [{
    source: '/etc/haproxy/haproxy.cfg.ctmpl',
    destination: '/etc/haproxy/haproxy.cfg',
    command: 'service haproxy restart'
  }]
end
```

to properly trigger the `service consul-template reload` on an Ubuntu 14.04 (I was tailing the logs).

**Comment by adamkrone** [comment]
Okay, that makes sense. I forgot about the `use_inline_resources` behavior.

It looks like they just released v0.6.0, so I'll probably be cutting a new release later this week once I get a chance to do some testing.

https://github.com/hashicorp/consul-template/releases

Thanks again!

**Comment by tgwizard** [comment]
Great, thanks!

**Pull request merged**
