### PR TITLE
Allow install_binary recipe to be run by itself.

### PR DESCRIPTION
**Pull request by mjcdiggity**
There are still some tests that failed while running test kitchen, but I wanted to check if this was an agreed upon way of resolving this issue. 

I can/will add specs/tests before this is merged. 

My use case is simply installing the binary.

### CODE REVIEW

**Comment by mjcdiggity** [comment]
@adamkrone any thoughts on this?

**Comment by scalp42** [comment]
@mjcdiggity what about just checking if the resource exists instead ? Keep the code cleaner.

**Comment by mjcdiggity** [comment]
There it is :+1:. Thanks, I'll update this soonish.

**Comment by mjcdiggity** [comment]
So I am trying to determine if the `consul-template` service is or will be present.

My first attempt involves: 

``` ruby
run_context.resource_collection.find do |r|
    r.name == 'consul-template'
end
```
 
This is used as an only if guard to the [`libarchive_file`](https://github.com/adamkrone/chef-consul-template/blob/master/recipes/install_binary.rb#L36-L43) resource. However, the resource at that time does not seem to have `service[consul-template]` defined, so not sure how else to solve this problem. 

Don't have an answer to this problem yet, but I'll keep thinking.

**Comment by mjcdiggity** [comment]
I just realized this would also prevent installing the binary, so this is not the right place to check. I guess there could be another resource that gets notified, but then I feel like we are back to sq 1, a not ideal solution.

**Comment by scalp42** [comment]
Any chance you can try:

```ruby
resource_exists = proc do |name|
  begin
    resources name
    true
  rescue Chef::Exceptions::ResourceNotFound
    false
  end
end

libarchive_file install_file do
  path download_path
  extract_to install_path
  mode 0755
  not_if { File.exist? install_path }
  action :extract
  notifies :restart, 'service[consul-template]', :delayed if resource_exists['service[consul-template]']
end
```

**Comment by mjcdiggity** [comment]
@scalp42 Tried that, seems to only return false when run at that point. `Chef::Exceptions::ResourceNotFound` does get raised.

**Comment by scalp42** [comment]
So wait I'm confused @mjcdiggity if it gets raised then the `notifies` should be ignored and not crash (meaning you can run the recipe by itself) no?

**Comment by mjcdiggity** [comment]
I'm saying it always get's raised, regardless if the recipe is run by itself or not. So the check to verify is resource collection has `service[consul-template]` always fails.

**Comment by scalp42** [comment]
That's really weird. What about:

```
resource_not_found = {}
begin
  resources('service[consul-template]')
rescue Chef::Exceptions::ResourceNotFound
  resource_not_found['service[consul-template]'] = true
end

libarchive_file install_file do
  path download_path
  extract_to install_path
  mode 0755
  not_if { File.exist? install_path }
  action :extract
  notifies :restart, 'service[consul-template]', :delayed unless resource_not_found['service[consul-template]']
end
```

**Comment by mjcdiggity** [comment]
Same behavior as the previous example, the resource is always not found.

**Comment by scalp42** [comment]
But that's what we want if you run the recipe by itself ?

**Comment by mjcdiggity** [comment]
Yes, but I'm testing with running the default recipe which runs `install_binary` and `service`.

Sorry I didnt notice this earlier, but right, since it can never be found it achieves its goal which is to be able to run the `install_binary` recipe in isolation. But if this change is run via the `default` recipe, then it will not notify the service, which is the same as removing the`notifies` action altogether. 

That is probably not the desired change, since I assume that is there to ensure if the binary version is updated then the service will be restarted, which makes sense.

**Comment by scalp42** [comment]
Gotcha, it's making more sense now. So `default` recipe is breaking the behavior you're saying ? I can't run the changes right now but something is not adding up but I can't figure it out without testing.

Thanks for clearing up though.

**Comment by scalp42** [comment]
Can you make sure however you're testing that the file is actually changing ? Meaning that `libarchive_file` resource actually triggers etc

**Comment by mjcdiggity** [comment]
Yeah I'll try some isolated tests later. I have been running it with the
`not_if` guard commented out.

Can you make sure however you're testing that the file is actually changing
? Meaning that libarchive_file resource actually triggers etc

—
Reply to this email directly or view it on GitHub
<https://github.com/adamkrone/chef-consul-template/pull/43#issuecomment-182046041>
.

**Comment by scalp42** [comment]
Yeah I'm not sure that `not_if` guard is even needed, could be the libarchive resource handling it directly, so better be safe :smile:

**Comment by adamkrone** [comment]
@mjcdiggity @scalp42 sorry I've been out of the loop on this one.

Is there a reason why we aren't taking a closer look at the original solution in the PR? Assuming we extract the install_file bits out into a helper that gets used in both recipes, I think switching to using subscribe makes sense.

**Comment by scalp42** [comment]
No other reasons than 1 place to notify vs 3 places to subscribe pretty much, whatever works :smile:

**Comment by adamkrone** [comment]
@scalp42 I don't have any particular preference, I was just wondering. Whatever is the easiest to implement/maintain is fine with me.

After some digging, I think I can explain why the resource is never found. I came across this article explaining [Chef's Two Pass Model](https://coderanger.net/two-pass/). If I'm understanding it correctly, the check is running during compile time, which means that the consul-template service has not been defined at that point (the service recipe always runs _after_ the install_binary recipe). The only way to force code to be evaluated during converge time is to include it in `not_if`, `only_if`, `ruby_block`, or `lazy`. I'm not sure if there's a way to setup a notification during converge like that. If not, we might be able to do something like:

```ruby
notifies :restart, 'service[consul-template]', :delayed if node['recipes'].include? 'consul-template::service'
```

**Comment by scalp42** [comment]
@adamkrone I'm still having doubts as the service resource would already exist at compile time. Need to test on a pristine box not on 2nd run.

**Comment by scalp42** [comment]
I'm going to test this afternoon :smile:

**Comment by scalp42** [comment]
@adamkrone @mjcdiggity I just ran a test with my changes and I can confirm that it works as intended:

- if `install_binary` is ran by itself, nothing blows up.
- if `default` is ran by itself, service restarts like usual (notification working as expected).

Here is the full log: https://gist.github.com/scalp42/f5af7b8c08b4471a5c25

The changes I made:

```ruby
resource_exists = proc do |name|
  begin
    resources name
    true
  rescue Chef::Exceptions::ResourceNotFound
    false
  end
end

libarchive_file install_file do
  path download_path
  extract_to install_path
  mode 0755
  not_if { File.exist? install_path }
  action :extract
  notifies :restart, 'service[consul-template]', :delayed if resource_exists['service[consul-template]']
end
```

**Comment by adamkrone** [comment]
@scalp42 Try running it on an already converged node. The consul-template config file notifies the service to restart whenever it's changed:

https://github.com/adamkrone/chef-consul-template/blob/master/recipes/service.rb#L67

You can see this in your log:

https://gist.github.com/scalp42/f5af7b8c08b4471a5c25#file-working-log-L619

In fact, that is the only delayed notification sent to `service[consul-template]'.

**Comment by scalp42** [comment]
@adamkrone I'm really confused. I'm going to run my changes on an already converged with both `default` and `install_binary` recipes but I don't see what would break ?

Running right now.

**Comment by scalp42** [comment]
Running my changes does not break anything on an already converged node.

- running `default` recipe: https://gist.github.com/scalp42/49ea47ff1411d0cccadf

- running `install_binary` recipe: https://gist.github.com/scalp42/0eb48cc01d4c11c23bc3

I think there's a bit of confusion here. I'm trying to reproduce this part:

    Yes, but I'm testing with running the default recipe which runs install_binary and service.

    Sorry I didnt notice this earlier, but right, since it can never be found it achieves its goal which is to be able to run the install_binary recipe in isolation. But if this change is run via the default recipe, then it will not notify the service, which is the same as removing thenotifies action altogether.

I'm going to downgrade the version of consul-template and see what happen.

**Comment by adamkrone** [comment]
@scalp42 the reason the restart notification exists is for when you update consul-template, the service needs to restart in order to use the new binary. Like @mjcdiggity said, using resources_exists doesn't help because it never returns true (the consul-template service resource doesn't exist until it's triggered in the service recipe).

**Comment by scalp42** [comment]
Okay I just did another run. Here is the scenario/results:

- node already converged `default` recipe with `0.12.2`
- modify version to `0.12.1` and run `install_binary`: https://gist.github.com/scalp42/a82a7d3d654606aaf1d9
- modify version to `0.12.0` and run `default` recipe: https://gist.github.com/scalp42/8a626640339e52c00d94

Every run was done back to back with my changes (just modified `node['consul_template']['version']` in between).

**Comment by adamkrone** [comment]
In the default log, the service is not restarted, which confirms what @mjcdiggity and I are seeing. A more direct way to see it would be to log out the value of `resource_exists['service[consul-template]']`. I would expect it to be false no matter which recipe you run.

**Comment by scalp42** [comment]
Yeah, sorry I got confused multitasking between things. `subscribe` sounds good to me.

**Comment by adamkrone** [comment]
@mjcdiggity it might be easiest to just stick with your original solution. The only tweak, which I mentioned earlier, would be to extract the lines that construct the install_file string into a function that can be shared between install_binary and default recipes.

**Comment by mjcdiggity** [comment]
@adamkrone @scalp42 Ok, will probably get to this over the weekend. Thanks for digging into the issue, and the useful info on [Chef's Two Pass Model](https://coderanger.net/two-pass/) (coderanger to the rescue).

**Comment by mjcdiggity** [comment]
@adamkrone I abstracted out the file logic into a helper module which is mixed-in to `Chef::Recipe` and `Chef::Resource` when needed. It appears to be working, although not sure of implications with other chef cookbooks. This update is also just to check if we agree on going down this route, and if so, I'll add some ChefSpec tests. 

Right now methods work off of chef attributes, but they could just as easily take parameters allowing them to stand on their own, and would be "easier" to test. 

Anyway, just let me know.

**Comment by adamkrone** [comment]
@mjcdiggity I think making them stand on their own might be better. I'm also not sure what effect it could have on other cookbooks, so it's probably worth playing it safe.

Thanks again for working on this!

**Comment by adamkrone** [comment]
@mjcdiggity Aside from the failing Travis build, is this ready? Assuming it's just Rubocop that's failing the build, I can take care of that. Let me know, as I'd like to merge this before I release a new version to the supermarket.

Thanks for all your help!

**Comment by mjcdiggity** [comment]
@adamkrone Yes, it's ready to go. I tried pushing a fix for the Rubocop failure, but if you can take of it than go ahead. Much appreciated.

**Pull request merged**
